name: my_awesome_ui
description: "A comprehensive styling utility and UI toolkit for Flutter applications."
version: 0.0.1
homepage: https://github.com/your_account/your_unique_package_name
repository: https://github.com/abdullahlotfy2010-sudo/my_awesome_ui
issue_tracker: https://github.com/abdullahlotfy2010-sudo/my_awesome_ui/issues

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: